# Generated by Django 3.0.2 on 2020-01-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='descricao',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
