# Generated by Django 3.0.2 on 2020-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200129_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='clientes.Departamento'),
        ),
    ]
