# Generated by Django 3.0.2 on 2020-01-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200129_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregado',
            name='departamentos',
        ),
    ]
