# Generated by Django 3.0.2 on 2020-01-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_empregado_departamentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empregado',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='Empregado',
            new_name='Cliente',
        ),
    ]
