# Generated by Django 3.0.2 on 2020-01-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20200129_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='clientes.Departamento'),
        ),
    ]
