# Generated by Django 3.0.2 on 2020-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='cliente_fotos'),
        ),
    ]
